-- MySQL Script generated by MySQL Workbench
-- Sat 06 May 2017 09:19:33 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_user_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_user_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_user_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_user_service` ;

-- -----------------------------------------------------
-- Table `ulbora_user_service`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_user_service`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ulbora_user_service`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_user_service`.`user` (
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `date_entered` DATE NOT NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(75) NOT NULL,
  `role_id` BIGINT NOT NULL,
  `client_id` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`username`, `client_id`),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `ulbora_user_service`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
